import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* Use the Head component to add the meta tag */}
      <Head>
        <meta name="theme-color" content="#317EFB" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
